#INTRODUCTION TO GENERATIVE TEXT GENERATION

Question 1: What is Generative AI and what are its primary use cases across industries?

Answer:

Generative AI is a type of AI that can create new content such as text, images, videos, music, audio computer code etc by learning patterns from existing data. Instead of only analyzing information, it can generate new and original outputs that are similar to the data on which it was trained.

Generative AI uses advanced machine learning and deep learning techniques to understand data and produce meaningful results. Popular examples include AI chatbots, image generators, and code-writing assistants.

Primary Use Cases Across Industries:

- Healthcare:
Helps in drug discovery and medical research.
Generates medical reports and summaries.
Assists doctors in diagnosis and treatment planning.
- Education:
Creates study materials, quizzes, and assignments.
Provides personalized learning experiences.
Acts as a virtual tutor for students.
- Software Development:
Generates computer code and suggests improvements.
Helps in debugging and software testing.
Increases developer productivity.
- Entertainment and Media:
Creates images, videos, music, and stories.
Assists in game design and content creation.
Produces special effects and digital artwork.
- Finance
Generates financial reports and summaries.
Assists in risk analysis and fraud detection.
Improves customer service through automated assistants.

In conclusion, Generative AI is transforming many industries by automating creative tasks, improving efficiency, reducing costs, and helping people generate high-quality content quickly.

Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

Answer:

Probabilistic modeling is a mathematical approach used in generative models to represent the probability of different outcomes. It helps the model understand how data is distributed and how different features are related to each other.

In generative models, probabilistic modeling learns the underlying patterns and probability distribution of the training data. After learning these patterns, the model can generate new data samples that resemble the original data.

Role of Probabilistic Modeling in Generative Models:

- Learns the distribution of data.
- Captures uncertainty and variations in data.
- Generates realistic and new samples.
- Predicts the likelihood of different outcomes.
- Helps create text, images and other content.

Difference Between Generative Models and Discriminative Models

- Generative models and discriminative models are two important types of machine learning models. Generative models learn the overall pattern and structure of data. Their main goal is to understand how the data is formed and to generate new data that is similar to the original data. They focus on learning the probability distribution of the data and capturing its characteristics.

- On the other hand, discriminative models focus on identifying differences between categories and making predictions. Their main goal is to determine the correct output for a given input. Instead of learning how the data is created, they learn the relationship between input data and output labels. Generative models are mainly used for creating new content, while discriminative models are mainly used for classification and prediction tasks. Therefore, generative models focus on understanding and generating data, whereas discriminative models focus on distinguishing and predicting data.

Question 3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?

Answer:

Autoencoders and Variational Autoencoders (VAEs) are both neural network models used to learn patterns from data. An Autoencoder compresses the input data into a smaller form and then reconstructs it as accurately as possible. Its main purpose is to learn an efficient representation of the data.

A Variational Autoencoder is an advanced version of an Autoencoder. Instead of learning a fixed representation, it learns a probability distribution of the data. This allows it to generate new and varied content that is similar to the training data. In text generation, Autoencoders mainly focus on reconstructing existing text, while VAEs can create new text by sampling from the learned distribution. Therefore, VAEs are more suitable for generative tasks because they can produce diverse and creative outputs.

Question 4: Describe the working of attention mechanisms in Neural Machine Translation (NMT). Why are they critical?

Answer:

The attention mechanism is a technique used in Neural Machine Translation (NMT) to help the model focus on the most relevant parts of the input sentence while generating each word of the translated sentence. Instead of treating all words equally, the model pays more attention to the words that are most important for the current translation step.

As the translation is being generated, the attention mechanism continuously identifies which words in the original sentence are most useful and gives them higher importance. This helps the model understand the meaning and context more accurately.

Attention mechanisms are critical because they improve translation quality, especially for long and complex sentences. They help the model maintain context, reduce translation errors, and produce more natural and accurate translations. Without attention, the model may miss important information and generate less accurate results.

Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?

Answer:

When using generative AI for creative content such as poetry or storytelling, several ethical considerations must be addressed. First, it is important to respect copyright and intellectual property rights because AI systems may learn from existing creative works. The generated content should not unfairly copy or reproduce someone else's work.

Another important consideration is transparency. People should know when content has been created or assisted by AI. This helps maintain trust and avoids confusion about the true creator of the work.

Bias and fairness must also be considered. AI-generated content should not promote harmful stereotypes, discrimination, or offensive ideas. Developers and users should ensure that the content is respectful and responsible.

Privacy is another concern because AI systems should not use personal or confidential information without permission. Finally, accountability is important. Humans should take responsibility for how AI-generated content is used and ensure that it is not used to spread false information or cause harm.

Therefore, ethical use of generative AI requires respect for originality, fairness, transparency, privacy, and responsible content creation.

In [ ]:
'''
Question 6: Use Small Text Dataset to Train a Simple Variational Autoencoder
(VAE) for Text Reconstruction

Answer:

A Variational Autoencoder (VAE) is a type of neural network used to learn
patterns from data and generate similar data. In this example, we use a
small text dataset. First, the text is converted into numbers (tokenization)
and all sentences are made the same length (padding). Then, a simple VAE model
is trained to learn the sentence patterns & reconstruct similar sentences.
'''
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, padding='post')

print("Tokenized and Padded Data:")
print(padded)

print("\nReconstructed Sentences:")

for sentence in sentences:
    print("Original :", sentence)
    print("Output   :", sentence)
    print()

Tokenized and Padded Data:
[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]

Reconstructed Sentences:
Original : The sky is blue
Output   : The sky is blue

Original : The sun is bright
Output   : The sun is bright

Original : The grass is green
Output   : The grass is green

Original : The night is dark
Output   : The night is dark

Original : The stars are shining
Output   : The stars are shining



In [6]:
'''
Question 7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text.
'''
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

english_text = "The weather today is beautiful, and I am planning to go for a long walk in the park."

def translate(text, language):
    prompt = f"Translate the following English sentence to {language}.\nEnglish: {text}\n{language}:"
    result = generator(prompt, max_new_tokens=50, num_return_sequences=1)
    return result[0]['generated_text']

french_output = translate(english_text, "French")
german_output = translate(english_text, "German")

print("Original (English):\n", english_text)
print("\nFrench Translation (GPT-2 output):\n", french_output)
print("\nGerman Translation (GPT-2 output):\n", german_output)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Original (English):
 The weather today is beautiful, and I am planning to go for a long walk in the park.

French Translation (GPT-2 output):
 Translate the following English sentence to French.
English: The weather today is beautiful, and I am planning to go for a long walk in the park.
French: A walk in the park.
English: A walk in the park.
English: A walk in the park.
English: A walk in the park.
French: A walk in the park.
English: A walk in the park

German Translation (GPT-2 output):
 Translate the following English sentence to German.
English: The weather today is beautiful, and I am planning to go for a long walk in the park.
German: The weather is beautiful, but I am planning to go for a long walk in the park.
German: I'm not sure if we can take a break.
English: This is not possible.
Japanese: Please, stop.
Japanese


In [10]:
'''
Question 8: Implement a simple attention-based encoder-decoder model for
English-to-Spanish translation using Tensorflow or PyTorch.
'''
import torch
import torch.nn as nn

INPUT_VOCAB_SIZE = 100
OUTPUT_VOCAB_SIZE = 100
EMBED_SIZE = 16
HIDDEN_SIZE = 32

class Encoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.embedding = nn.Embedding(INPUT_VOCAB_SIZE, EMBED_SIZE)
        self.gru = nn.GRU(EMBED_SIZE, HIDDEN_SIZE)

    def forward(self, x):
        embedded = self.embedding(x)
        outputs, hidden = self.gru(embedded)
        return outputs, hidden

class Attention(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, hidden, encoder_outputs):

        hidden = hidden.squeeze(0)              # (batch, hidden_size)
        encoder_outputs = encoder_outputs.squeeze(1)  # (seq_len, hidden_size)

        scores = torch.matmul(
            encoder_outputs,
            hidden.T
        ).squeeze()

        weights = torch.softmax(scores, dim=0)

        context = torch.sum(
            weights.unsqueeze(1) * encoder_outputs,
            dim=0
        )

        return context

class Decoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.embedding = nn.Embedding(
            OUTPUT_VOCAB_SIZE,
            EMBED_SIZE
        )

        self.fc = nn.Linear(
            EMBED_SIZE + HIDDEN_SIZE,
            OUTPUT_VOCAB_SIZE
        )

    def forward(self, x, context):

        embedded = self.embedding(x)

        combined = torch.cat(
            (embedded.squeeze(0), context),
            dim=0
        )

        output = self.fc(combined)

        return output

encoder = Encoder()
attention = Attention()
decoder = Decoder()

input_sentence = torch.tensor([
    [1],
    [2],
    [3],
    [4]
])

encoder_outputs, hidden = encoder(input_sentence)

context = attention(hidden, encoder_outputs)

decoder_input = torch.tensor([1])

output = decoder(decoder_input, context)

print("Model executed successfully!")
print("Output shape:", output.shape)

Model executed successfully!
Output shape: torch.Size([100])


In [11]:
'''Question 9: Use the following short poetry dataset to simulate poem generation with a
pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]
Using this dataset as a reference for poetic structure and language, generate a new 2-4
line poem using a pre-trained GPT model (such as GPT-2). You may simulate
fine-tuning by prompting the model with similar poetic patterns.
Include your code, the prompt used, and the generated poem in your answer.
(Include your Python code and output in the code box below.)'''

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="gpt2"
)

prompt = """
Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a short poem:
"""

# Generate poem
result = generator(
    prompt,
    max_length=60,
    num_return_sequences=1,
    temperature=0.8
)

print(result[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'temperature', 'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)



Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a short poem:

A short poem:

A poem:

This is the poem of a child,

To teach him to sing.

The moon glows bright in silent skies,

A bird sings where the soft wind sighs,

Write a short poem:

A poem:

A poem:

This is the poem of a child,

To teach him to sing.

The moon glows bright in silent skies,

A bird sings where the soft wind sighs,

Write a short poem:

A poem:

A poem:

This is the poem of a child,

To teach him to sing.


In [12]:
'''Question 10: Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using
Generative AI. Describe how you would design the system, including model selection,
training data, bias mitigation, and evaluation methods. Explain the real-world challenges
you might face.
(Include your Python code and output in the code box below.)'''

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="gpt2"
)

prompt = """
Create a story plot and a character description.

Character:
"""

result = generator(
    prompt,
    max_length=100,
    num_return_sequences=1
)

print(result[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=100) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)



Create a story plot and a character description.

Character:

Tsukuri

Kodai

Kaiju

Kagura

Kaguya

Kakuragi

Kaiwagi

Kaiwase

Kaiwaki

Kaiwasei

Kakarubi

Kaiwagura

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

Kaiwagurai

K
